name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies (receipt service)
      working-directory: receipt_service
      run: pip install -r requirements.txt

    - name: Run tests (receipt service)
      working-directory: receipt_service
      run: pytest -q

    - name: Install dependencies (rules service)
      working-directory: rules_service
      run: pip install -r requirements.txt

    - name: Run tests (rules service)
      working-directory: rules_service
      run: pytest -q